services:
#    client.example:
#        class: ClientBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
      update_point:
          class: ClientBundle\Services\EquipeService
      update_etat:
          class: ClientBundle\Services\GroupeService