services:
#    client.example:
#        class: ClientBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
      update_point:
          class: ClientBundle\Services\EquipeService
      update_etat:
          class: ClientBundle\Services\GroupeService
      traitement:
                class: ClientBundle\Services\TraitementPHF
                arguments: [ "@doctrine.orm.entity_manager" ]
      quart:
                class: ClientBundle\Services\QuartService
                arguments: [ "@doctrine.orm.entity_manager" ]
      demi:
                class: ClientBundle\Services\DemiService
                arguments: [ "@doctrine.orm.entity_manager" ]
      finale:
                class: ClientBundle\Services\FinalService
                arguments: [ "@doctrine.orm.entity_manager" ]